frolf/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
# from django.conf.urls import url, include
from django.urls import path
import core.views
import score.views

urlpatterns = [
    path('', core.views.default, name="index"),
    path('admin/', admin.site.urls),
    path('login/', auth_views.login, {'template_name': 'login.html'}),
    path('logout/', auth_views.logout, {'template_name': 'logout.html'}),
    path('match_results_view', score.views.competition_results_list),
    path('match_results_single/<int:id>/', score.views.competition_results_single),
    path('course_create', score.views.course_create),
    path('course_created/<int:course_id>/', score.views.course_update),
    path('course_read/<int:course_id>/', score.views.course_read),
    path('match_results_create', score.views.competition_create),
    path('match_results_add/<int:course_id>/<int:players>/<int:comp_id>/', score.views.competition_update),
    # path('match_results_add', score.views.default, name="add"),

]

score/models.py
from django.db import models


class Player(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=100, blank=False)

    def __str__(self):
        return self.name


class Hole(models.Model):
    course = models.ForeignKey('score.Course',
                               on_delete=models.CASCADE)
    number = models.IntegerField()
    par = models.IntegerField()

    def __str__(self):
        return "{0} hole {1}".format(self.course, self.number)


class Competition(models.Model):
    date = models.DateField()
    game_number = models.IntegerField()
    notes = models.TextField(null=False, blank=True)
    course = models.ForeignKey('score.Course',
                               on_delete=models.PROTECT)

    def get_absolute_url(self):
        return "/match_results_single/{0}/".format(self.id)

    def __str__(self):
        return "{0} on {1} # {2}".format(self.course,
                                         self.date,
                                         self.game_number)


class Throw(models.Model):
    player = models.ForeignKey('score.Player',
                               on_delete=models.PROTECT)
    competition = models.ForeignKey('score.Competition',
                                    on_delete=models.PROTECT)
    hole = models.ForeignKey('score.Hole',
                             on_delete=models.PROTECT)
    throws = models.IntegerField()

    def __str__(self):
        return "{0} {1} {2}".format(self.competition,
                                    self.player,
                                    self.hole)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

{#    <link rel="stylesheet" href="{% static 'css/base.css' %}">#}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>{% block title %}frolf{% endblock %}</title>
</head>
<body>

<nav class="navbar navbar-expand-md bg-dark navbar-dark">

    <!-- toggle button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>

    <a class="navbar-brand" href="/">frolf</a>

    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
            </li>

            {% if user.is_superuser %}
            <li class="nav-item">
                <a class="nav-link" href="/admin">Admin</a>
            </li>
            {% endif %}

            <li class="nav-item">
                <a class="nav-link" href="/course_create">Course Add</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="/match_results_create">Match Add</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="/match_results_view">Match Results</a>
            </li>
        </ul>
    </div>
</nav>
<div class="container-fluid">
    {% block display %}
    {% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{%  extends 'base.html' %}

{% block display %}
<h1 align="center">Welcome to frolf</h1>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Frolf Login</title>
</head>
<body>
<h2>Please log in to continue</h2>
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form}}
    <input type="submit" value="OK">
</form>
{% endblock %}

</body>
</html>

templates/match_results_single.html
{%  extends 'base.html' %}
<title>{% block title %}Match Results{% endblock %}</title>

{% block display %}
    <table class=table">
        <thead>
        <tr>
            <th scope="row" width="20%">Course</th>
            <th scope="row" width="20%">Date</th>
            <th scope="row" width="20%">Game</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ match_meta.course.name }}</td>
                <td>{{ match_meta.date }}</td>
                <td>{{ match_meta.game_number }}</td>
            </tr>
        </tbody>
    </table>
<hr>
    <table class="table table-sm">
        <thead>
        </thead>
        <tbody>
            <tr>
                <th scope="row">Hole</th>
                {% for k, v in course_meta.par.items %}
                    <td align="right" width="5%">{{ k }}</td>
                {% endfor %}
            </tr>
            <tr></tr>
            <tr>
                <th>Par</th>
                {% for k, v in course_meta.par.items %}
                    <td align="right">{{ v }}</td>
                {% endfor %}
            </tr>
        </tbody>
    </table>

<hr>
<h5>Match Notes</h5>
{{ match_meta.notes }}

{% endblock %}

templates/match_view.html
{%  extends 'base.html' %}

{% block display %}
    <h2>
        Match View
    </h2>

    <table class="table table-hover">
    <thead>
        <th>Course</th>
        <th>Date</th>
        <th>Match</th>
        <th>Notes</th>
    </thead>
    <tbody>
    {% for match in matches %}
        <td><a href="{{ match.get_absolute_url }}">{{ match.course }}</a></td>
        <td>{{ match.date }}</td>
        <td>{{ match.game_number }}</td>
        <td>{{ match.notes }}</td>
    {% endfor %}
    </tbody>
    </table>


{% endblock %}

templates/score_competition_c.html
{%  extends 'base.html' %}
<title>{% block title %}Match Entry{% endblock %}</title>

{% block display %}

<br>
<div class="container">
        <form action="" method="post">
            {% csrf_token %}
            <table class="table-sm">
                <tbody>
                    <tr>
                        <th>{{ form.course_select.label }}</th>
                        <td>{{ form.course_select }}</td>
                    </tr>
                    <tr>
                        <th>{{ form.match_date.label }}</th>
                        <td>{{ form.match_date }}</td>
                    </tr>
                    <tr>
                        <th>{{ form.match_number.label }}</th>
                        <td>{{ form.match_number }}</td>
                    </tr>
                    <tr>
                        <th>{{ form.player_count.label }}</th>
                        <td>{{ form.player_count }}</td>
                    </tr>                    <tr>
                        <th>{{ form.notes.label }}</th>
                        <td>{{ form.notes }}</td>
                    </tr>
                </tbody>
            </table>
            <input type="Submit" value="Next" />
        </form>
</div>
{% endblock %}

templates/score_competition_cu.html
{%  extends 'base.html' %}
<title>{% block title %}Match Entry{% endblock %}</title>

{% block display %}

</p>
<div class="container">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <input type="Submit" value="Submit" />
    </form>

</div>
{% endblock %}

templates/score_competition_list_table.html
{%  extends 'base.html' %}

{% block display %}
    <h2>
        Match View
    </h2>

    <table class="table table-hover">
    <thead>
        <th>Course</th>
        <th>Date</th>
        <th>Round</th>
        <th>Notes</th>
    </thead>
    <tbody>
    {% for match in matches %}
        <tr>
        <td><a href="{{ match.get_absolute_url }}">{{ match.course }}</a></td>
        <td>{{ match.date }}</td>
        <td>{{ match.game_number }}</td>
        <td>{{ match.notes }}</td>
        </tr>
    {% endfor %}
    </tbody>
    </table>


{% endblock %}

templates/score_competition_r.html
{%  extends 'base.html' %}
<title>{% block title %}Match Results{% endblock %}</title>

{% block display %}
    <table>
        <thead>
        <tr>
            <th scope="row" width="20%">Course</th>
            <th scope="row" width="20%">Date</th>
            <th scope="row" width="20%">Game</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ match_meta.course.name }}</td>
                <td>{{ match_meta.date }}</td>
                <td>{{ match_meta.game_number }}</td>
            </tr>
        </tbody>
    </table>
<hr>
    <table class="table table-sm table-hover">
        <thead>
            <tr class="table-active" id="hole">
                <th scope="row">Hole</th>
                {% for k, v in course_meta.par.items %}
                    <td align="right" width="5%">{{ k }}</td>
                {% endfor %}
            </tr>
            <tr id="par">
                <th>Par</th>
                {% for k, v in course_meta.par.items %}
                    <td align="right">{{ v }}</td>
                {% endfor %}
            </tr>
        </thead>
        <tbody class="table-hover">
        {% for player, throw_set in comp_data.throws.items %}
            <tr>
                <th>{{ player }}</th>
                {% for hole, throw in throw_set.items %}
                    <td align="right">{{ throw }}</td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>

<hr>
<h5>Match Notes</h5>
{{ match_meta.notes }}

{% endblock %}

templates/score_competition_u.html
{%  extends 'base.html' %}
<title>{% block title %}Match Entry{% endblock %}</title>

{% block display %}

<br>
<div class="container">
    <h4>Course{{ course_meta.course.name }}</h4>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <input type="Submit" value="Next" />
    </form>

</div>
{% endblock %}

templates/score_course_c.html
{%  extends 'base.html' %}
<title>{% block title %}Match Entry{% endblock %}</title>

{% block display %}
    <br>
    <div class="container">
            <form action="" method="post">
                {% csrf_token %}
                <table class="table-sm">
                    <tbody>
                        <tr>
                            <th>Course Name</th>
                            <td>{{ form.course_name }}</td>
                        </tr>
                        <tr>
                            <th>Number of Holes</th>
                            <td>{{ form.hole_count }}</td>
                        </tr>
                    </tbody>
                </table>
                <input type="Submit" value="Next" />
            </form>
    </div>
{% endblock %}

templates/score_course_cu.html
{%  extends 'base.html' %}
<title>{% block title %}Match Entry{% endblock %}</title>

{% block display %}
    </p>
    <div class="container">
        <div class="row">
            <form action="" method="post">
                {% csrf_token %}
                {{ form }}
                <input type="Submit" value="Submit" />
            </form>
        </div>
    </div>
{% endblock %}

templates/score_course_r.html
{%  extends 'base.html' %}
<title>{% block title %}Match Entry{% endblock %}</title>

{% block display %}
    <br>
    <div class="container">
        <div class="table-responsive">
            <table class="table">
                <tr>
                    <td>Number</td>
                    {% for hole in holes %}
                    <td>
                        {{ hole.number }}
                    </td>
                    {% endfor %}
                </tr>
                <tr>
                    <td>Par</td>
                    {% for hole in holes %}
                    <td>
                        {{ hole.par }}
                    </td>
                    {% endfor %}
                </tr>
            </table>
        </div>
    </div>
{% endblock %}

templates/score_course_u.html
{%  extends 'base.html' %}
<title>{% block title %}Match Entry{% endblock %}</title>

{% block display %}
    <br>
    <div class="container">
        <div class="row">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="Submit" value="Create Course" />
            </form>
        </div>
    </div>
{% endblock %}